{
  "swagger": "2.0",
  "schemes": [
    "https"
  ],
  "host": "acrapi.azurecr-test.io",
  "info": {
    "description": "V2 API definition for the Azure Container Registry runtime",
    "title": "Azure Container Registry",
    "version": "2018-08-10-preview",
    "x-origin": [
      {
        "format": "swagger",
        "url": "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/containerregistry/data-plane/Microsoft.ContainerRegistry/preview/2018-08-10/containerregistry.json",
        "version": "2.0"
      }
    ],
    "x-preferred": true,
    "x-providerName": "azurecr-test.io",
    "x-serviceName": "containerregistry"
  },
  "produces": [
    "application/json"
  ],
  "securityDefinitions": {
    "registry_auth": {
      "type": "basic"
    }
  },
  "security": [
    {
      "registry_auth": []
    }
  ],
  "parameters": {
    "digest": {
      "description": "Digest of a desired BLOB",
      "in": "path",
      "name": "digest",
      "required": true,
      "type": "string",
      "x-ms-parameter-location": "method"
    },
    "metadata": {
      "description": "Name of the metadata",
      "in": "path",
      "name": "metadata",
      "required": true,
      "type": "string",
      "x-ms-parameter-location": "method"
    },
    "name": {
      "description": "Name of the image (including the namespace)",
      "in": "path",
      "name": "name",
      "required": true,
      "type": "string",
      "x-ms-parameter-location": "method"
    },
    "property": {
      "description": "Name of the property",
      "in": "path",
      "name": "property",
      "required": true,
      "type": "string",
      "x-ms-parameter-location": "method"
    },
    "queryDigest": {
      "description": "filter by digest",
      "in": "query",
      "name": "digest",
      "required": false,
      "type": "string",
      "x-ms-parameter-location": "method"
    },
    "queryLast": {
      "description": "query parameter for the last item in previou query",
      "in": "query",
      "name": "last",
      "required": false,
      "type": "string",
      "x-ms-parameter-location": "method"
    },
    "queryNum": {
      "description": "query parameter for max number of items",
      "in": "query",
      "name": "n",
      "required": false,
      "type": "string",
      "x-ms-parameter-location": "method"
    },
    "queryOrderBy": {
      "description": "orderby query parameter",
      "in": "query",
      "name": "orderby",
      "required": false,
      "type": "string",
      "x-ms-parameter-location": "method"
    },
    "reference": {
      "description": "A tag or a digest, pointing to a specific image",
      "in": "path",
      "name": "reference",
      "required": true,
      "type": "string",
      "x-ms-parameter-location": "method"
    }
  },
  "tags": [
    {
      "description": "Root API",
      "name": "v2"
    },
    {
      "description": "Everything about manfests",
      "name": "Manifest"
    },
    {
      "description": "Everything about tags",
      "name": "Tag"
    },
    {
      "description": "Everything about layers",
      "name": "Layer"
    },
    {
      "description": "Everyting about repository",
      "name": "Repository"
    },
    {
      "description": "ACR APIs related to repositories",
      "name": "AcrRepository"
    },
    {
      "description": "ACR APIs related to manifests",
      "name": "AcrManifest"
    },
    {
      "description": "ACR APIs related to tags",
      "name": "AcrTag"
    }
  ],
  "paths": {
    "/acr/v1/_catalog": {
      "get": {
        "description": "List respositories",
        "operationId": "GetAcrRepositories",
        "parameters": [
          {
            "description": "query parameter for the last item in previou query",
            "in": "query",
            "name": "last",
            "required": false,
            "type": "string"
          },
          {
            "description": "query parameter for max number of items",
            "in": "query",
            "name": "n",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a list of repositories",
            "schema": {
              "$ref": "#/definitions/Repositories"
            }
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        },
        "tags": [
          "AcrRepository"
        ],
        "x-ms-examples": {
          "Get repositories in a registry": {
            "parameters": {},
            "responses": {
              "200": {
                "body": {
                  "repositories": [
                    "production/apline",
                    "testing/apline"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/acr/v1/{name}": {
      "delete": {
        "description": "Delete a respository",
        "operationId": "DeleteAcrRepository",
        "parameters": [
          {
            "description": "Name of the image (including the namespace)",
            "in": "path",
            "name": "name",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "202": {
            "description": "The repoisotry is deleted",
            "schema": {
              "$ref": "#/definitions/DeletedRepository"
            }
          },
          "404": {
            "description": "Image doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        },
        "tags": [
          "AcrRepository"
        ],
        "x-ms-examples": {
          "Delete a repository": {
            "parameters": {
              "name": "nanoserver"
            },
            "responses": {
              "202": {
                "body": {
                  "manifestsDeleted": [
                    "sha256:e31831d63f77a0a6d74ef5b16df619a50808dac842190d07ae24e8b520d159fa"
                  ],
                  "tagsDeleted": [
                    "4.7.2-20180814-windowsservercore-1709"
                  ]
                }
              },
              "404": {}
            }
          }
        }
      },
      "get": {
        "description": "Get respository attributes",
        "operationId": "GetAcrRepositoryAttributes",
        "parameters": [
          {
            "description": "Name of the image (including the namespace)",
            "in": "path",
            "name": "name",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a list of attributes",
            "schema": {
              "$ref": "#/definitions/RepositoryAttributes"
            }
          },
          "404": {
            "description": "Image doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        },
        "tags": [
          "AcrRepository",
          "AcrMetadata"
        ],
        "x-ms-examples": {
          "Get details of repository": {
            "parameters": {
              "name": "nanoserver"
            },
            "responses": {
              "200": {
                "body": {
                  "changeableAttributes": {
                    "deleteEnabled": true,
                    "listEnabled": true,
                    "readEnabled": true,
                    "writeEnabled": true
                  },
                  "createdTime": "2018-09-06T06:17:20.9531248Z",
                  "imageName": "nanoserver",
                  "lastUpdateTime": "2018-09-07T16:30:46.6583219Z",
                  "manifestCount": 2,
                  "registry": "acrapi.azurecr-test.io",
                  "tagCount": 2
                }
              },
              "404": {}
            }
          }
        }
      },
      "patch": {
        "consumes": [
          "application/json"
        ],
        "description": "Update attributes of a repository",
        "operationId": "UpdateAcrRepositoryAttributes",
        "parameters": [
          {
            "description": "Name of the image (including the namespace)",
            "in": "path",
            "name": "name",
            "required": true,
            "type": "string"
          },
          {
            "description": "Repository attribute value",
            "in": "body",
            "name": "value",
            "required": false,
            "schema": {
              "$ref": "#/definitions/ChangeableAttributes"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "The attributes is updated"
          },
          "404": {
            "description": "Image doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        },
        "tags": [
          "AcrRepository",
          "AcrMetadata"
        ],
        "x-ms-examples": {
          "Update repository attributes": {
            "parameters": {
              "name": "nanoserver",
              "writeEnabled": false
            },
            "responses": {
              "204": {},
              "404": {}
            }
          }
        }
      }
    },
    "/acr/v1/{name}/_manifests": {
      "get": {
        "description": "List manifests of a repository",
        "operationId": "GetAcrManifests",
        "parameters": [
          {
            "description": "Name of the image (including the namespace)",
            "in": "path",
            "name": "name",
            "required": true,
            "type": "string"
          },
          {
            "description": "query parameter for the last item in previou query",
            "in": "query",
            "name": "last",
            "required": false,
            "type": "string"
          },
          {
            "description": "query parameter for max number of items",
            "in": "query",
            "name": "n",
            "required": false,
            "type": "string"
          },
          {
            "description": "orderby query parameter",
            "in": "query",
            "name": "orderby",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a list of manifests",
            "schema": {
              "$ref": "#/definitions/AcrManifests"
            }
          },
          "404": {
            "description": "Image doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        },
        "tags": [
          "AcrManifest",
          "AcrMetadata"
        ],
        "x-ms-examples": {
          "Get details of repository": {
            "parameters": {
              "name": "nanoserver"
            },
            "responses": {
              "200": {
                "body": {
                  "imageName": "nanoserver",
                  "manifests": [
                    {
                      "architecture": "amd64",
                      "changeableAttributes": {
                        "deleteEnabled": true,
                        "listEnabled": true,
                        "readEnabled": true,
                        "writeEnabled": true
                      },
                      "createdTime": "2018-09-06T06:17:20.9983915Z",
                      "digest": "sha256:110d2b6c84592561338aa040b1b14b7ab81c2f9edbd564c2285dd7d70d777086",
                      "lastUpdateTime": "2018-09-06T06:17:20.9983915Z",
                      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
                      "os": "windows",
                      "tags": [
                        "4.7.2-20180905-nanoserver-1803"
                      ]
                    },
                    {
                      "architecture": "amd64",
                      "changeableAttributes": {
                        "deleteEnabled": true,
                        "listEnabled": true,
                        "readEnabled": true,
                        "writeEnabled": true
                      },
                      "createdTime": "2018-09-07T16:30:46.5651701Z",
                      "digest": "sha256:7af5cd1dde3e8f5c2c9103860afa4ca871a6075373b6564b0e7b1b47866dab52",
                      "lastUpdateTime": "2018-09-07T16:30:46.5651701Z",
                      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
                      "os": "windows",
                      "tags": [
                        "4.7.2-20180906-nanoserver-1803"
                      ]
                    }
                  ],
                  "registry": "acrapi.azurecr-test.io"
                }
              },
              "404": {}
            }
          }
        }
      }
    },
    "/acr/v1/{name}/_manifests/{reference}": {
      "get": {
        "description": "Get manifest attributes",
        "operationId": "GetAcrManifestAttributes",
        "parameters": [
          {
            "description": "Name of the image (including the namespace)",
            "in": "path",
            "name": "name",
            "required": true,
            "type": "string"
          },
          {
            "description": "A digest pointing to a specific image",
            "in": "path",
            "name": "reference",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "List of attributes",
            "schema": {
              "$ref": "#/definitions/AcrManifestAttributes"
            }
          },
          "404": {
            "description": "Manifest doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        },
        "tags": [
          "AcrManifest",
          "AcrMetadata"
        ],
        "x-ms-examples": {
          "Get manifest attributes": {
            "parameters": {
              "name": "nanoserver",
              "reference": "sha256:110d2b6c84592561338aa040b1b14b7ab81c2f9edbd564c2285dd7d70d777086"
            },
            "responses": {
              "200": {
                "body": {
                  "imageName": "nanoserver",
                  "manifest": {
                    "architecture": "amd64",
                    "changeableAttributes": {
                      "deleteEnabled": true,
                      "listEnabled": true,
                      "readEnabled": true,
                      "writeEnabled": true
                    },
                    "createdTime": "2018-09-06T06:17:20.9983915Z",
                    "digest": "sha256:110d2b6c84592561338aa040b1b14b7ab81c2f9edbd564c2285dd7d70d777086",
                    "lastUpdateTime": "2018-09-06T06:17:20.9983915Z",
                    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
                    "os": "windows",
                    "tags": [
                      "4.7.2-20180905-nanoserver-1803"
                    ]
                  },
                  "registry": "acrapi.azurecr-test.io"
                }
              },
              "404": {}
            }
          }
        }
      },
      "patch": {
        "consumes": [
          "application/json"
        ],
        "description": "Update attributes of a manifest",
        "operationId": "UpdateAcrManifestAttributes",
        "parameters": [
          {
            "description": "Name of the image (including the namespace)",
            "in": "path",
            "name": "name",
            "required": true,
            "type": "string"
          },
          {
            "description": "A tag or a digest, pointing to a specific image",
            "in": "path",
            "name": "reference",
            "required": true,
            "type": "string"
          },
          {
            "description": "Changeable attribute value",
            "in": "body",
            "name": "value",
            "required": false,
            "schema": {
              "$ref": "#/definitions/ChangeableAttributes"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "The attributes are updated"
          },
          "404": {
            "description": "Manifest doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        },
        "tags": [
          "AcrManifest",
          "AcrMetadata"
        ],
        "x-ms-examples": {
          "Update attributes of a manifest": {
            "parameters": {
              "name": "nanoserver",
              "reference": "sha256:110d2b6c84592561338aa040b1b14b7ab81c2f9edbd564c2285dd7d70d777086",
              "value": "{\"writeEnabled\": false}"
            },
            "responses": {
              "204": {},
              "404": {}
            }
          }
        }
      }
    },
    "/acr/v1/{name}/_tags": {
      "get": {
        "description": "List tags of a repository",
        "operationId": "GetAcrTags",
        "parameters": [
          {
            "description": "Name of the image (including the namespace)",
            "in": "path",
            "name": "name",
            "required": true,
            "type": "string"
          },
          {
            "description": "query parameter for the last item in previou query",
            "in": "query",
            "name": "last",
            "required": false,
            "type": "string"
          },
          {
            "description": "query parameter for max number of items",
            "in": "query",
            "name": "n",
            "required": false,
            "type": "string"
          },
          {
            "description": "orderby query parameter",
            "in": "query",
            "name": "orderby",
            "required": false,
            "type": "string"
          },
          {
            "description": "filter by digest",
            "in": "query",
            "name": "digest",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Tag details of a repository",
            "schema": {
              "$ref": "#/definitions/AcrRepositoryTags"
            }
          },
          "404": {
            "description": "Image doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        },
        "tags": [
          "AcrTag",
          "AcrMetadata"
        ],
        "x-ms-examples": {
          "Get tags of a repository": {
            "parameters": {
              "name": "nanoserver"
            },
            "responses": {
              "200": {
                "body": {
                  "imageName": "nanoserver",
                  "registry": "acrapi.azurecr-test.io",
                  "tags": [
                    {
                      "changeableAttributes": {
                        "deleteEnabled": true,
                        "listEnabled": true,
                        "readEnabled": true,
                        "writeEnabled": true
                      },
                      "createdTime": "2018-09-06T06:17:21.0856539Z",
                      "digest": "sha256:110d2b6c84592561338aa040b1b14b7ab81c2f9edbd564c2285dd7d70d777086",
                      "lastUpdateTime": "2018-09-06T06:17:21.0856539Z",
                      "name": "4.7.2-20180905-nanoserver-1803",
                      "signed": false
                    },
                    {
                      "changeableAttributes": {
                        "deleteEnabled": true,
                        "listEnabled": true,
                        "readEnabled": true,
                        "writeEnabled": true
                      },
                      "createdTime": "2018-09-06T16:30:43.3860166Z",
                      "digest": "sha256:7af5cd1dde3e8f5c2c9103860afa4ca871a6075373b6564b0e7b1b47866dab52",
                      "lastUpdateTime": "2018-09-07T16:30:46.7022734Z",
                      "name": "4.7.2-20180906-nanoserver-1803",
                      "signed": false
                    }
                  ]
                }
              },
              "404": {}
            }
          }
        }
      }
    },
    "/acr/v1/{name}/_tags/{reference}": {
      "delete": {
        "consumes": [
          "application/json"
        ],
        "description": "Delete tag",
        "operationId": "DeleteAcrTag",
        "parameters": [
          {
            "description": "Name of the image (including the namespace)",
            "in": "path",
            "name": "name",
            "required": true,
            "type": "string"
          },
          {
            "description": "A tag name of the image",
            "in": "path",
            "name": "reference",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "The tag is deleted"
          },
          "404": {
            "description": "Tag doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        },
        "tags": [
          "AcrTag",
          "AcrMetadata"
        ],
        "x-ms-examples": {
          "Update attributes of a manifest": {
            "parameters": {
              "name": "nanoserver",
              "reference": "4.7.2-20180905-nanoserver-1803"
            },
            "responses": {
              "204": {},
              "404": {}
            }
          }
        }
      },
      "get": {
        "description": "Get manifest attributes by tag",
        "operationId": "GetAcrTagAttributes",
        "parameters": [
          {
            "description": "Name of the image (including the namespace)",
            "in": "path",
            "name": "name",
            "required": true,
            "type": "string"
          },
          {
            "description": "A tag name of the image",
            "in": "path",
            "name": "reference",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Tag attributes",
            "schema": {
              "$ref": "#/definitions/AcrTagAttributes"
            }
          },
          "404": {
            "description": "Tag doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        },
        "tags": [
          "AcrTag",
          "AcrMetadata"
        ],
        "x-ms-examples": {
          "Get manifest attributes": {
            "parameters": {
              "name": "test/bash",
              "reference": "tagName"
            },
            "responses": {
              "200": {
                "imageName": "test/bash",
                "registry": "acrapi.azurecr-test.io",
                "tag": {
                  "changeableAttributes": {
                    "deleteEnabled": true,
                    "listEnabled": true,
                    "readEnabled": true,
                    "writeEnabled": false
                  },
                  "createdTime": "2018-10-05T20:54:24.1286047Z",
                  "digest": "sha256:eabe547f78d4c18c708dd97ec3166cf7464cc651f1cbb67e70d407405b7ad7b6",
                  "lastUpdateTime": "2018-10-05T20:54:24.1286047Z",
                  "name": "tagName",
                  "signed": false
                }
              },
              "404": {}
            }
          }
        }
      },
      "patch": {
        "consumes": [
          "application/json"
        ],
        "description": "Update tag attributes",
        "operationId": "UpdateAcrTagAttributes",
        "parameters": [
          {
            "description": "Name of the image (including the namespace)",
            "in": "path",
            "name": "name",
            "required": true,
            "type": "string"
          },
          {
            "description": "A tag name of the image",
            "in": "path",
            "name": "reference",
            "required": true,
            "type": "string"
          },
          {
            "description": "Changeable attribute value",
            "in": "body",
            "name": "value",
            "required": false,
            "schema": {
              "$ref": "#/definitions/ChangeableAttributes"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "The attributes are updated"
          },
          "404": {
            "description": "Manifest doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        },
        "tags": [
          "AcrTag",
          "AcrMetadata"
        ],
        "x-ms-examples": {
          "Update attributes of a manifest": {
            "parameters": {
              "name": "nanoserver",
              "reference": "4.7.2-20180905-nanoserver-1803",
              "value": "{\"writeEnabled\": false}"
            },
            "responses": {
              "204": {},
              "404": {}
            }
          }
        }
      }
    },
    "/v2/": {
      "get": {
        "description": "Tells whether this Docker Registry instance supports Docker Registry HTTP API v2",
        "operationId": "GetDockerRegistryV2Support",
        "responses": {
          "200": {
            "description": "Successful response. API v2 supported"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        },
        "tags": [
          "v2"
        ],
        "x-ms-examples": {
          "Check Docker Registry V2 Support": {
            "parameters": {},
            "responses": {
              "200": {}
            }
          }
        }
      }
    },
    "/v2/_catalog": {
      "get": {
        "description": "List respositories",
        "operationId": "GetRepositories",
        "parameters": [
          {
            "description": "query parameter for the last item in previou query",
            "in": "query",
            "name": "last",
            "required": false,
            "type": "string"
          },
          {
            "description": "query parameter for max number of items",
            "in": "query",
            "name": "n",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a list of repositories",
            "schema": {
              "$ref": "#/definitions/Repositories"
            }
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        },
        "tags": [
          "Repository"
        ],
        "x-ms-examples": {
          "Get repositories in a registry": {
            "parameters": {},
            "responses": {
              "200": {
                "body": {
                  "repositories": [
                    "production/apline",
                    "testing/apline"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/v2/{name}/manifests/{reference}": {
      "get": {
        "description": "Pulls the image manifest file associated with the specified name and reference. Reference may be a tag or a digest",
        "operationId": "GetManifest",
        "parameters": [
          {
            "description": "Name of the image (including the namespace)",
            "in": "path",
            "name": "name",
            "required": true,
            "type": "string"
          },
          {
            "description": "A tag or a digest, pointing to a specific image",
            "in": "path",
            "name": "reference",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the requested manifest file",
            "schema": {
              "$ref": "#/definitions/Manifest"
            }
          },
          "404": {
            "description": "Image doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        },
        "tags": [
          "Manifest"
        ],
        "x-ms-examples": {
          "Get manifest": {
            "parameters": {
              "name": "nanoserver",
              "reference": "4.7.2-20180905-nanoserver-1803"
            },
            "responses": {
              "200": {
                "body": {
                  "architecture": "amd64",
                  "fsLayers": [
                    {
                      "blobSum": "sha256:b9bd2388a23447de788a154093dd9b89a822725492b7bfafab9015ce93b871e0"
                    },
                    {
                      "blobSum": "sha256:c1f8a6fa5e3d3117531e76b205d7370057628908490cf961c71b92f915fa6254"
                    },
                    {
                      "blobSum": "sha256:1f7d468f830cb0ed4beb8edc9438f18096e8c682e56a35242f60e6c61b718b30"
                    },
                    {
                      "blobSum": "sha256:e46172273a4e4384e1eec7fb01091c828a256ea0f87b30f61381fba9bc511371"
                    }
                  ],
                  "history": [
                    {
                      "v1Compatibility": "{\"architecture\":\"amd64\",\"config\":{\"Hostname\":\"\",\"Domainname\":\"\",\"User\":\"ContainerUser\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":null,\"Cmd\":[\"cmd\",\"/C\",\"type C:\\\\hello.txt\"],\"ArgsEscaped\":true,\"Image\":\"sha256:efe84b3d2d41c56b455412b710c700ccd28ca370d6804522a733ba6bcdae8e00\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":null},\"container\":\"0a87ffdd343b17ed11efbbd7607330e6c2119579cf9d3a90611f44a26761ab82\",\"container_config\":{\"Hostname\":\"0a87ffdd343b\",\"Domainname\":\"\",\"User\":\"ContainerUser\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":null,\"Cmd\":[\"cmd\",\"/S\",\"/C\",\"#(nop) \",\"CMD [\\\"cmd\\\" \\\"/C\\\" \\\"type C:\\\\\\\\hello.txt\\\"]\"],\"ArgsEscaped\":true,\"Image\":\"sha256:efe84b3d2d41c56b455412b710c700ccd28ca370d6804522a733ba6bcdae8e00\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":{}},\"created\":\"2018-09-06T05:19:24.0396273Z\",\"docker_version\":\"18.03.1-ee-2\",\"id\":\"ab4de54a8b50f761f99f27212594a5bcf6d7d2a82b0a056b8376cab244ecdf65\",\"os\":\"windows\",\"os.version\":\"10.0.17134.228\",\"parent\":\"446a68d4429c55d85a52160454e3437fe5aea4e51f9010623d010b5f14c1c8f6\"}"
                    },
                    {
                      "v1Compatibility": "{\"id\":\"446a68d4429c55d85a52160454e3437fe5aea4e51f9010623d010b5f14c1c8f6\",\"parent\":\"70a9fdb67496aa42b7fc7162133e635f8c66bd0bcfdab80d7dcd4c2342e57e20\",\"created\":\"2018-09-06T05:19:22.749573Z\",\"container_config\":{\"Cmd\":[\"cmd /S /C #(nop) COPY file:c6a48931fdbc0a16819a7896580105073d7c78961ee467d2512d8a5d68e011de in C: \"]}}"
                    },
                    {
                      "v1Compatibility": "{\"id\":\"70a9fdb67496aa42b7fc7162133e635f8c66bd0bcfdab80d7dcd4c2342e57e20\",\"parent\":\"c25e10f4a7396863709cbbb107c1ee148fee59b8b20994a42817d4cc6c6981bd\",\"created\":\"2018-08-06T18:09:11.4272822Z\",\"container_config\":{\"Cmd\":[\"Install update 10.0.17134.228\"]}}"
                    },
                    {
                      "v1Compatibility": "{\"id\":\"c25e10f4a7396863709cbbb107c1ee148fee59b8b20994a42817d4cc6c6981bd\",\"created\":\"2018-04-11T22:12:30.263Z\",\"container_config\":{\"Cmd\":[\"Apply image 10.0.17134.1\"]}}"
                    }
                  ],
                  "name": "nanoserver",
                  "schemaVersion": 1,
                  "signatures": [
                    {
                      "header": {
                        "alg": "ES256",
                        "jwk": {
                          "crv": "P-256",
                          "kid": "WGXM:EYWQ:DA53:LQUP:BCWG:5RDG:S3ZM:ETH7:VMQS:WWKZ:EWDG:V74Q",
                          "kty": "EC",
                          "x": "OxZ9k5BVjPZ7jb3BmBD4X0d8MVPJqfF4NeSe8reoqnY",
                          "y": "EaCqTe4-vYwhk7qU6Bs2-AeLGOVtCe_-IY2MdE0Vfyc"
                        }
                      },
                      "protected": "eyJmb3JtYXRMZW5ndGgiOjI5ODYsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAxOC0wOS0yMFQyMzo0MTo1MloifQ",
                      "signature": "p73LfotMGD8nNXz2g9YX2XtSllb4GI5-b3vjqP5N0nkv8QXg-r5z_omGiVbOZE2BYG1X_4TIN23l1KSEqsXxOg"
                    }
                  ],
                  "tag": "4.7.2-20180905-nanoserver-1803"
                }
              },
              "404": {}
            }
          }
        }
      }
    },
    "/v2/{name}/tags/list": {
      "get": {
        "description": "Fetch the tags under the repository identified by 'name'",
        "operationId": "GetTagList",
        "parameters": [
          {
            "description": "Name of the image (including the namespace)",
            "in": "path",
            "name": "name",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Gives a list of tags for the names repository.",
            "schema": {
              "$ref": "#/definitions/RepositoryTags"
            }
          },
          "404": {
            "description": "Image doesn't exist"
          },
          "default": {
            "description": "ACR error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/AcrErrors"
            }
          }
        },
        "tags": [
          "Tag"
        ],
        "x-ms-examples": {
          "List tags": {
            "parameters": {
              "name": "nanoserver"
            },
            "responses": {
              "200": {
                "body": {
                  "name": "nanoserver",
                  "tags": [
                    "4.7.2-20180905-nanoserver-1803",
                    "4.7.2-20180906-nanoserver-1803"
                  ]
                }
              },
              "404": {}
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AcrErrorInfo": {
      "description": "Error information",
      "properties": {
        "code": {
          "description": "Error code",
          "type": "string"
        },
        "detail": {
          "description": "Error details",
          "type": "string"
        },
        "message": {
          "description": "Error message",
          "type": "string"
        }
      }
    },
    "AcrErrors": {
      "description": "Acr error response describing why the operation failed",
      "properties": {
        "errors": {
          "description": "Array of detailed error",
          "items": {
            "$ref": "#/definitions/AcrErrorInfo"
          },
          "type": "array"
        }
      }
    },
    "AcrManifestAttributes": {
      "description": "Manifest attributes details",
      "example": {
        "imageName": "nanoserver",
        "manifest": {
          "architecture": "amd64",
          "changeableAttributes": {
            "deleteEnabled": true,
            "listEnabled": true,
            "readEnabled": true,
            "writeEnabled": true
          },
          "createdTime": "2018-09-06T06:17:20.9983915Z",
          "digest": "sha256:110d2b6c84592561338aa040b1b14b7ab81c2f9edbd564c2285dd7d70d777086",
          "lastUpdateTime": "2018-09-06T06:17:20.9983915Z",
          "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
          "os": "windows",
          "tags": [
            "4.7.2-20180905-nanoserver-1803"
          ]
        },
        "registry": "acrapi.azurecr-test.io"
      },
      "properties": {
        "imageName": {
          "description": "Image name",
          "type": "string"
        },
        "manifest": {
          "$ref": "#/definitions/AcrManifestAttributesBase",
          "description": "Manifest attributes"
        },
        "registry": {
          "description": "Registry name",
          "type": "string"
        }
      }
    },
    "AcrManifestAttributesBase": {
      "description": "Manifest details",
      "example": {
        "architecture": "architecture",
        "changeableAttributes": {
          "deleteEnabled": true,
          "listEnabled": true,
          "readEnabled": true,
          "writeEnabled": true
        },
        "createdTime": "createdTime",
        "digest": "digest",
        "lastUpdateTime": "lastUpdateTime",
        "mediaType": "mediaType",
        "os": "os",
        "tags": [
          "tags",
          "tags"
        ]
      },
      "properties": {
        "architecture": {
          "description": "CPU architecture",
          "type": "string"
        },
        "changeableAttributes": {
          "$ref": "#/definitions/ChangeableAttributes",
          "description": "Changeable attributes"
        },
        "createdTime": {
          "description": "Created time",
          "type": "string"
        },
        "digest": {
          "description": "Manifest digest",
          "type": "string"
        },
        "lastUpdateTime": {
          "description": "Last update time",
          "type": "string"
        },
        "mediaType": {
          "description": "Media type",
          "type": "string"
        },
        "os": {
          "description": "Operating system",
          "type": "string"
        },
        "tags": {
          "description": "List of tags",
          "items": {
            "description": "Tag name",
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "AcrManifests": {
      "description": "Manifest attributes",
      "example": {
        "imageName": "imageName",
        "manifests": [
          {
            "architecture": "architecture",
            "changeableAttributes": {
              "deleteEnabled": true,
              "listEnabled": true,
              "quarantineDetails": "quarantineDetails",
              "quarantineState": "quarantineState",
              "readEnabled": true,
              "writeEnabled": true
            },
            "createdTime": "createdTime",
            "digest": "digest",
            "lastUpdateTime": "lastUpdateTime",
            "mediaType": "mediaType",
            "os": "os",
            "tags": [
              "tags",
              "tags"
            ]
          },
          {
            "architecture": "architecture",
            "changeableAttributes": {
              "deleteEnabled": true,
              "listEnabled": true,
              "quarantineDetails": "quarantineDetails",
              "quarantineState": "quarantineState",
              "readEnabled": true,
              "writeEnabled": true
            },
            "createdTime": "createdTime",
            "digest": "digest",
            "lastUpdateTime": "lastUpdateTime",
            "mediaType": "mediaType",
            "os": "os",
            "tags": [
              "tags",
              "tags"
            ]
          }
        ],
        "registry": "registry"
      },
      "properties": {
        "imageName": {
          "description": "Image name",
          "type": "string"
        },
        "manifests": {
          "description": "List of manifests",
          "items": {
            "$ref": "#/definitions/AcrManifestAttributesBase",
            "description": "Manifest details"
          },
          "type": "array"
        },
        "registry": {
          "description": "Registry name",
          "type": "string"
        }
      }
    },
    "AcrRepositoryTags": {
      "description": "List of tag details",
      "example": {
        "imageName": "imageName",
        "registry": "registry",
        "tags": [
          {
            "changeableAttributes": {
              "deleteEnabled": true,
              "listEnabled": true,
              "readEnabled": true,
              "writeEnabled": true
            },
            "createdTime": "createdTime",
            "digest": "digest",
            "lastUpdateTime": "lastUpdateTime",
            "name": "name",
            "quarantineState": "quarantineState",
            "signed": true
          },
          {
            "changeableAttributes": {
              "deleteEnabled": true,
              "listEnabled": true,
              "readEnabled": true,
              "writeEnabled": true
            },
            "createdTime": "createdTime",
            "digest": "digest",
            "lastUpdateTime": "lastUpdateTime",
            "name": "name",
            "quarantineState": "quarantineState",
            "signed": true
          }
        ]
      },
      "properties": {
        "imageName": {
          "description": "Image name",
          "type": "string"
        },
        "registry": {
          "description": "Registry name",
          "type": "string"
        },
        "tags": {
          "description": "List of tag attribute details",
          "items": {
            "$ref": "#/definitions/AcrTagAttributesBase"
          },
          "type": "array",
          "x-ms-client-name": "TagsAttributes"
        }
      }
    },
    "AcrTagAttributes": {
      "description": "Tag attributes",
      "example": {
        "imageName": "imageName",
        "registry": "registry",
        "tag": {
          "changeableAttributes": {
            "deleteEnabled": true,
            "listEnabled": true,
            "readEnabled": true,
            "writeEnabled": true
          },
          "createdTime": "createdTime",
          "digest": "digest",
          "lastUpdateTime": "lastUpdateTime",
          "name": "name",
          "quarantineState": "quarantineState",
          "signed": true
        }
      },
      "properties": {
        "imageName": {
          "description": "Image name",
          "type": "string"
        },
        "registry": {
          "description": "Registry name",
          "type": "string"
        },
        "tag": {
          "$ref": "#/definitions/AcrTagAttributesBase",
          "description": "List of tag attribute details",
          "x-ms-client-name": "TagAttributes"
        }
      }
    },
    "AcrTagAttributesBase": {
      "description": "Tag attribute details",
      "example": {
        "changeableAttributes": {
          "deleteEnabled": true,
          "listEnabled": true,
          "readEnabled": true,
          "writeEnabled": true
        },
        "createdTime": "2018-08-10T17:28:44.1082945Z",
        "digest": "sha256:0873c923e00e0fd2ba78041bfb64a105e1ecb7678916d1f7776311e45bf5634b",
        "lastUpdateTime": "2018-08-10T17:28:44.1082945Z",
        "name": "tagname",
        "signed": true
      },
      "properties": {
        "changeableAttributes": {
          "$ref": "#/definitions/ChangeableAttributes",
          "description": "Changeable attributes"
        },
        "createdTime": {
          "description": "Tag created time",
          "type": "string"
        },
        "digest": {
          "description": "Tag digest",
          "type": "string"
        },
        "lastUpdateTime": {
          "description": "Tag last update time",
          "type": "string"
        },
        "name": {
          "description": "Tag name",
          "type": "string"
        },
        "signed": {
          "description": "Is signed",
          "type": "boolean"
        }
      }
    },
    "ChangeableAttributes": {
      "example": {
        "deleteEnabled": true,
        "listEnabled": true,
        "readEnabled": true,
        "writeEnabled": true
      },
      "properties": {
        "deleteEnabled": {
          "description": "Delete enabled",
          "type": "boolean"
        },
        "listEnabled": {
          "description": "List enabled",
          "type": "boolean"
        },
        "readEnabled": {
          "description": "Read enabled",
          "type": "boolean"
        },
        "writeEnabled": {
          "description": "Write enabled",
          "type": "boolean"
        }
      }
    },
    "DeletedRepository": {
      "description": "Deleted repository",
      "properties": {
        "manifestsDeleted": {
          "description": "SHA of the deleted image",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "tagsDeleted": {
          "description": "Tag of the deleted image",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      }
    },
    "ImageHistory": {
      "description": "A list of unstructured historical data for v1 compatibility",
      "example": {
        "v1Compatibility": "v1 compatibility info"
      },
      "properties": {
        "v1Compatibility": {
          "description": "The raw v1 compatibility information",
          "type": "string"
        }
      }
    },
    "ImageLayer": {
      "description": "Image layer information",
      "example": {
        "blobSum": "sha256:1f7d468f830cb0ed4beb8edc9438f18096e8c682e56a35242f60e6c61b718b30"
      },
      "properties": {
        "blobSum": {
          "description": "SHA of an image layer",
          "type": "string"
        }
      }
    },
    "ImageSignature": {
      "description": "Signature of a signed manifest",
      "example": {
        "header": {
          "alg": "ES256",
          "jwk": {
            "crv": "P-256",
            "kid": "WGXM:EYWQ:DA53:LQUP:BCWG:5RDG:S3ZM:ETH7:VMQS:WWKZ:EWDG:V74Q",
            "kty": "EC",
            "x": "OxZ9k5BVjPZ7jb3BmBD4X0d8MVPJqfF4NeSe8reoqnY",
            "y": "EaCqTe4-vYwhk7qU6Bs2-AeLGOVtCe_-IY2MdE0Vfyc"
          }
        },
        "protected": "eyJmb3JtYXRMZW5ndGgiOjI5ODYsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAxOC0wOS0yMFQyMzo0MTo1MloifQ",
        "signature": "p73LfotMGD8nNXz2g9YX2XtSllb4GI5-b3vjqP5N0nkv8QXg-r5z_omGiVbOZE2BYG1X_4TIN23l1KSEqsXxOg"
      },
      "properties": {
        "header": {
          "$ref": "#/definitions/JWK",
          "description": "A JSON web signature"
        },
        "protected": {
          "description": "The signed protected header",
          "type": "string",
          "x-ms-client-name": "protectedHeader"
        },
        "signature": {
          "description": "A signature for the image manifest, signed by a libtrust private key",
          "type": "string"
        }
      }
    },
    "JWK": {
      "description": "A JSON web signature",
      "properties": {
        "alg": {
          "description": "The algorithm used to sign or encrypt the JWT",
          "type": "string"
        },
        "jwk": {
          "$ref": "#/definitions/JWKHeader"
        }
      }
    },
    "JWKHeader": {
      "description": "JSON web key parameter",
      "properties": {
        "crv": {
          "description": "crv value",
          "type": "string"
        },
        "kid": {
          "description": "kid value",
          "type": "string"
        },
        "kty": {
          "description": "kty value",
          "type": "string"
        },
        "x": {
          "description": "x value",
          "type": "string"
        },
        "y": {
          "description": "y value",
          "type": "string"
        }
      }
    },
    "Manifest": {
      "description": "Returns the requested manifest file",
      "example": {
        "fsLayers": [
          {
            "blobSum": "sha256:1f7d468f830cb0ed4beb8edc9438f18096e8c682e56a35242f60e6c61b718b30"
          },
          {
            "blobSum": "sha256:2f7d468f830cb0ed4beb8edc9438f18096e8c682e56a35242f60e6c61b718b31"
          }
        ],
        "history": "history",
        "name": "name",
        "signatures": [
          {
            "header": {
              "alg": "ES256",
              "jwk": {
                "crv": "P-256",
                "kid": "WGXM:EYWQ:DA53:LQUP:BCWG:5RDG:S3ZM:ETH7:VMQS:WWKZ:EWDG:V74Q",
                "kty": "EC",
                "x": "OxZ9k5BVjPZ7jb3BmBD4X0d8MVPJqfF4NeSe8reoqnY",
                "y": "EaCqTe4-vYwhk7qU6Bs2-AeLGOVtCe_-IY2MdE0Vfyc"
              }
            },
            "protected": "eyJmb3JtYXRMZW5ndGgiOjI5ODYsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAxOC0wOS0yMFQyMzo0MTo1MloifQ",
            "signature": "p73LfotMGD8nNXz2g9YX2XtSllb4GI5-b3vjqP5N0nkv8QXg-r5z_omGiVbOZE2BYG1X_4TIN23l1KSEqsXxOg"
          }
        ],
        "tag": "tag"
      },
      "properties": {
        "architecture": {
          "description": "CPU architecture",
          "type": "string"
        },
        "fsLayers": {
          "description": "List of layer information",
          "items": {
            "$ref": "#/definitions/ImageLayer"
          },
          "type": "array"
        },
        "history": {
          "description": "Image history",
          "items": {
            "$ref": "#/definitions/ImageHistory"
          },
          "type": "array",
          "x-ms-client-name": "ImageHistories"
        },
        "name": {
          "description": "Image name",
          "type": "string"
        },
        "schemaVersion": {
          "description": "Schema version",
          "type": "number"
        },
        "signatures": {
          "description": "Image signature",
          "items": {
            "$ref": "#/definitions/ImageSignature"
          },
          "type": "array"
        },
        "tag": {
          "description": "Image tag",
          "type": "string"
        }
      }
    },
    "ManifestAttributes_manifest": {
      "description": "List of manifest attributes",
      "example": {
        "quarantineTag": "quarantineTag",
        "references": [
          {
            "architecture": "architecture",
            "digest": "digest",
            "os": "os"
          },
          {
            "architecture": "architecture",
            "digest": "digest",
            "os": "os"
          }
        ]
      },
      "properties": {
        "quarantineTag": {
          "description": "Quarantine tag name",
          "type": "string"
        },
        "references": {
          "description": "List of manifest attributes details",
          "items": {
            "$ref": "#/definitions/ManifestAttributes_manifest_references",
            "description": "Manifest attributes details"
          },
          "type": "array"
        }
      }
    },
    "ManifestAttributes_manifest_references": {
      "description": "Manifest attributes details",
      "example": {
        "architecture": "architecture",
        "digest": "digest",
        "os": "os"
      },
      "properties": {
        "architecture": {
          "description": "CPU architecture",
          "type": "string"
        },
        "digest": {
          "description": "Manifest digest",
          "type": "string"
        },
        "os": {
          "description": "Operating system",
          "type": "string"
        }
      }
    },
    "ManifestChangeableAttributes": {
      "description": "Changeable attributes",
      "example": {
        "deleteEnabled": true,
        "listEnabled": true,
        "quarantineDetails": "quarantineDetails",
        "quarantineState": "quarantineState",
        "readEnabled": true,
        "writeEnabled": true
      },
      "properties": {
        "deleteEnabled": {
          "description": "Delete enabled",
          "type": "boolean"
        },
        "listEnabled": {
          "description": "List enabled",
          "type": "boolean"
        },
        "quarantineDetails": {
          "description": "Quarantine details",
          "type": "string"
        },
        "quarantineState": {
          "description": "Quarantine state",
          "type": "string"
        },
        "readEnabled": {
          "description": "Read enabled",
          "type": "boolean"
        },
        "writeEnabled": {
          "description": "Write enabled",
          "type": "boolean"
        }
      }
    },
    "Repositories": {
      "description": "List of repositories",
      "example": {
        "repositories": [
          "production/apline",
          "testing/apline"
        ]
      },
      "properties": {
        "repositories": {
          "description": "Repository names",
          "items": {
            "type": "string"
          },
          "type": "array",
          "x-ms-client-name": "Names"
        }
      }
    },
    "RepositoryAttributes": {
      "description": "Repository attributes",
      "example": {
        "changeableAttributes": {
          "deleteEnabled": true,
          "listEnabled": true,
          "readEnabled": true,
          "writeEnabled": true
        },
        "createdTime": "2018-09-07T16:30:46.6583219Z",
        "imageName": "imageName",
        "lastUpdateTime": "2018-09-07T16:30:46.6583219Z",
        "manifestCount": 2,
        "registry": "registryname.azurecr.io",
        "tagCount": 6
      },
      "properties": {
        "changeableAttributes": {
          "$ref": "#/definitions/ChangeableAttributes",
          "description": "Changeable attributes"
        },
        "createdTime": {
          "description": "Image created time",
          "type": "string"
        },
        "imageName": {
          "description": "Image name",
          "type": "string"
        },
        "lastUpdateTime": {
          "description": "Image last update time",
          "type": "string"
        },
        "manifestCount": {
          "description": "Number of the manifests",
          "type": "number"
        },
        "registry": {
          "description": "Registry name",
          "type": "string"
        },
        "tagCount": {
          "description": "Number of the tags",
          "type": "number"
        }
      },
      "type": "object"
    },
    "RepositoryTags": {
      "description": "Result of the request to list tags of the image",
      "example": {
        "name": "name",
        "tags": [
          "tags",
          "tags"
        ]
      },
      "properties": {
        "name": {
          "description": "Name of the image",
          "type": "string"
        },
        "tags": {
          "description": "List of tags",
          "items": {
            "description": "Tag name",
            "type": "string"
          },
          "type": "array"
        }
      }
    },
    "TagAttributes": {
      "description": "Tag attributes",
      "example": {
        "imageName": "imageName",
        "registry": "registry",
        "tag": {
          "signatureRecord": "signatureRecord"
        }
      },
      "properties": {
        "imageName": {
          "description": "Image name",
          "type": "string"
        },
        "registry": {
          "description": "Registry name",
          "type": "string"
        },
        "tag": {
          "$ref": "#/definitions/TagAttributes_tag",
          "description": "Tag attributes"
        }
      }
    },
    "TagAttributes_tag": {
      "description": "Tag",
      "example": {
        "signatureRecord": "signatureRecord"
      },
      "properties": {
        "signatureRecord": {
          "description": "SignatureRecord value",
          "type": "string"
        }
      }
    }
  }
}
